# Generated by Django 3.1.1 on 2020-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201208_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
